// Code generated by MockGen. DO NOT EDIT.
// Source: client/interface.go
//
// Generated by this command:
//
//	mockgen -source=client/interface.go -destination=mocks/Instana-api_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	"github.com/instana/instana-go-client/api"
	rest "github.com/instana/instana-go-client/shared/rest"
	gomock "go.uber.org/mock/gomock"
)

// MockInstanaAPI is a mock of InstanaAPI interface.
type MockInstanaAPI struct {
	ctrl     *gomock.Controller
	recorder *MockInstanaAPIMockRecorder
	isgomock struct{}
}

// MockInstanaAPIMockRecorder is the mock recorder for MockInstanaAPI.
type MockInstanaAPIMockRecorder struct {
	mock *MockInstanaAPI
}

// NewMockInstanaAPI creates a new mock instance.
func NewMockInstanaAPI(ctrl *gomock.Controller) *MockInstanaAPI {
	mock := &MockInstanaAPI{ctrl: ctrl}
	mock.recorder = &MockInstanaAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanaAPI) EXPECT() *MockInstanaAPIMockRecorder {
	return m.recorder
}

// APITokens mocks base method.
func (m *MockInstanaAPI) APITokens() rest.RestResource[*api.APIToken] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APITokens")
	ret0, _ := ret[0].(rest.RestResource[*api.APIToken])
	return ret0
}

// APITokens indicates an expected call of APITokens.
func (mr *MockInstanaAPIMockRecorder) APITokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APITokens", reflect.TypeOf((*MockInstanaAPI)(nil).APITokens))
}

// AlertingChannels mocks base method.
func (m *MockInstanaAPI) AlertingChannels() rest.RestResource[*api.AlertingChannel] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertingChannels")
	ret0, _ := ret[0].(rest.RestResource[*api.AlertingChannel])
	return ret0
}

// AlertingChannels indicates an expected call of AlertingChannels.
func (mr *MockInstanaAPIMockRecorder) AlertingChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertingChannels", reflect.TypeOf((*MockInstanaAPI)(nil).AlertingChannels))
}

// AlertingConfigurations mocks base method.
func (m *MockInstanaAPI) AlertingConfigurations() rest.RestResource[*api.AlertingConfiguration] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertingConfigurations")
	ret0, _ := ret[0].(rest.RestResource[*api.AlertingConfiguration])
	return ret0
}

// AlertingConfigurations indicates an expected call of AlertingConfigurations.
func (mr *MockInstanaAPIMockRecorder) AlertingConfigurations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertingConfigurations", reflect.TypeOf((*MockInstanaAPI)(nil).AlertingConfigurations))
}

// ApplicationAlertConfigs mocks base method.
func (m *MockInstanaAPI) ApplicationAlertConfigs() rest.RestResource[*api.ApplicationAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplicationAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.ApplicationAlertConfig])
	return ret0
}

// ApplicationAlertConfigs indicates an expected call of ApplicationAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) ApplicationAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplicationAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).ApplicationAlertConfigs))
}

// ApplicationConfigs mocks base method.
func (m *MockInstanaAPI) ApplicationConfigs() rest.RestResource[*api.ApplicationConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplicationConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.ApplicationConfig])
	return ret0
}

// ApplicationConfigs indicates an expected call of ApplicationConfigs.
func (mr *MockInstanaAPIMockRecorder) ApplicationConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplicationConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).ApplicationConfigs))
}

// AutomationActions mocks base method.
func (m *MockInstanaAPI) AutomationActions() rest.RestResource[*api.AutomationAction] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutomationActions")
	ret0, _ := ret[0].(rest.RestResource[*api.AutomationAction])
	return ret0
}

// AutomationActions indicates an expected call of AutomationActions.
func (mr *MockInstanaAPIMockRecorder) AutomationActions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutomationActions", reflect.TypeOf((*MockInstanaAPI)(nil).AutomationActions))
}

// AutomationPolicies mocks base method.
func (m *MockInstanaAPI) AutomationPolicies() rest.RestResource[*api.AutomationPolicy] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutomationPolicies")
	ret0, _ := ret[0].(rest.RestResource[*api.AutomationPolicy])
	return ret0
}

// AutomationPolicies indicates an expected call of AutomationPolicies.
func (mr *MockInstanaAPIMockRecorder) AutomationPolicies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutomationPolicies", reflect.TypeOf((*MockInstanaAPI)(nil).AutomationPolicies))
}

// BuiltinEventSpecifications mocks base method.
func (m *MockInstanaAPI) BuiltinEventSpecifications() rest.ReadOnlyRestResource[*api.BuiltinEventSpecification] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuiltinEventSpecifications")
	ret0, _ := ret[0].(rest.ReadOnlyRestResource[*api.BuiltinEventSpecification])
	return ret0
}

// BuiltinEventSpecifications indicates an expected call of BuiltinEventSpecifications.
func (mr *MockInstanaAPIMockRecorder) BuiltinEventSpecifications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuiltinEventSpecifications", reflect.TypeOf((*MockInstanaAPI)(nil).BuiltinEventSpecifications))
}

// CustomDashboards mocks base method.
func (m *MockInstanaAPI) CustomDashboards() rest.RestResource[*api.CustomDashboard] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomDashboards")
	ret0, _ := ret[0].(rest.RestResource[*api.CustomDashboard])
	return ret0
}

// CustomDashboards indicates an expected call of CustomDashboards.
func (mr *MockInstanaAPIMockRecorder) CustomDashboards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomDashboards", reflect.TypeOf((*MockInstanaAPI)(nil).CustomDashboards))
}

// CustomEventSpecifications mocks base method.
func (m *MockInstanaAPI) CustomEventSpecifications() rest.RestResource[*api.CustomEventSpecification] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomEventSpecifications")
	ret0, _ := ret[0].(rest.RestResource[*api.CustomEventSpecification])
	return ret0
}

// CustomEventSpecifications indicates an expected call of CustomEventSpecifications.
func (mr *MockInstanaAPIMockRecorder) CustomEventSpecifications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomEventSpecifications", reflect.TypeOf((*MockInstanaAPI)(nil).CustomEventSpecifications))
}

// GlobalApplicationAlertConfigs mocks base method.
func (m *MockInstanaAPI) GlobalApplicationAlertConfigs() rest.RestResource[*api.ApplicationAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalApplicationAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.ApplicationAlertConfig])
	return ret0
}

// GlobalApplicationAlertConfigs indicates an expected call of GlobalApplicationAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) GlobalApplicationAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalApplicationAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).GlobalApplicationAlertConfigs))
}

// Groups mocks base method.
func (m *MockInstanaAPI) Groups() rest.RestResource[*api.Group] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(rest.RestResource[*api.Group])
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockInstanaAPIMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockInstanaAPI)(nil).Groups))
}

// HostAgents mocks base method.
func (m *MockInstanaAPI) HostAgents() rest.ReadOnlyRestResource[*api.HostAgent] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HostAgents")
	ret0, _ := ret[0].(rest.ReadOnlyRestResource[*api.HostAgent])
	return ret0
}

// HostAgents indicates an expected call of HostAgents.
func (mr *MockInstanaAPIMockRecorder) HostAgents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HostAgents", reflect.TypeOf((*MockInstanaAPI)(nil).HostAgents))
}

// InfraAlertConfigs mocks base method.
func (m *MockInstanaAPI) InfraAlertConfigs() rest.RestResource[*api.InfraAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfraAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.InfraAlertConfig])
	return ret0
}

// InfraAlertConfigs indicates an expected call of InfraAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) InfraAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfraAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).InfraAlertConfigs))
}

// LogAlertConfigs mocks base method.
func (m *MockInstanaAPI) LogAlertConfigs() rest.RestResource[*api.LogAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.LogAlertConfig])
	return ret0
}

// LogAlertConfigs indicates an expected call of LogAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) LogAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).LogAlertConfigs))
}

// MaintenanceWindowConfigs mocks base method.
func (m *MockInstanaAPI) MaintenanceWindowConfigs() rest.RestResource[*api.MaintenanceWindow] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaintenanceWindowConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.MaintenanceWindow])
	return ret0
}

// MaintenanceWindowConfigs indicates an expected call of MaintenanceWindowConfigs.
func (mr *MockInstanaAPIMockRecorder) MaintenanceWindowConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaintenanceWindowConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).MaintenanceWindowConfigs))
}

// MobileAlertConfigs mocks base method.
func (m *MockInstanaAPI) MobileAlertConfigs() rest.RestResource[*api.MobileAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MobileAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.MobileAlertConfig])
	return ret0
}

// MobileAppConfig mock implementation
func (m *MockInstanaAPI) MobileAppConfig() rest.RestResource[*api.MobileAppConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MobileAppConfig")
	ret0, _ := ret[0].(rest.RestResource[*api.MobileAppConfig])
	return ret0
}

// MobileAlertConfigs indicates an expected call of MobileAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) MobileAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MobileAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).MobileAlertConfigs))
}

// Roles mocks base method.
func (m *MockInstanaAPI) Roles() rest.RestResource[*api.Role] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Roles")
	ret0, _ := ret[0].(rest.RestResource[*api.Role])
	return ret0
}

// Roles indicates an expected call of Roles.
func (mr *MockInstanaAPIMockRecorder) Roles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Roles", reflect.TypeOf((*MockInstanaAPI)(nil).Roles))
}

// SliConfigs mocks base method.
func (m *MockInstanaAPI) SliConfigs() rest.RestResource[*api.SliConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SliConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.SliConfig])
	return ret0
}

// SliConfigs indicates an expected call of SliConfigs.
func (mr *MockInstanaAPIMockRecorder) SliConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SliConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).SliConfigs))
}

// SloAlertConfigs mocks base method.
func (m *MockInstanaAPI) SloAlertConfigs() rest.RestResource[*api.SloAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SloAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.SloAlertConfig])
	return ret0
}

// SloAlertConfigs indicates an expected call of SloAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) SloAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SloAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).SloAlertConfigs))
}

// SloConfigs mocks base method.
func (m *MockInstanaAPI) SloConfigs() rest.RestResource[*api.SloConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SloConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.SloConfig])
	return ret0
}

// SloConfigs indicates an expected call of SloConfigs.
func (mr *MockInstanaAPIMockRecorder) SloConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SloConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).SloConfigs))
}

// SloCorrectionConfigs mocks base method.
func (m *MockInstanaAPI) SloCorrectionConfigs() rest.RestResource[*api.SloCorrectionConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SloCorrectionConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.SloCorrectionConfig])
	return ret0
}

// SloCorrectionConfigs indicates an expected call of SloCorrectionConfigs.
func (mr *MockInstanaAPIMockRecorder) SloCorrectionConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SloCorrectionConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).SloCorrectionConfigs))
}

// SyntheticAlertConfigs mocks base method.
func (m *MockInstanaAPI) SyntheticAlertConfigs() rest.RestResource[*api.SyntheticAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyntheticAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.SyntheticAlertConfig])
	return ret0
}

// SyntheticAlertConfigs indicates an expected call of SyntheticAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) SyntheticAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyntheticAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).SyntheticAlertConfigs))
}

// SyntheticLocations mocks base method.
func (m *MockInstanaAPI) SyntheticLocations() rest.ReadOnlyRestResource[*api.SyntheticLocation] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyntheticLocations")
	ret0, _ := ret[0].(rest.ReadOnlyRestResource[*api.SyntheticLocation])
	return ret0
}

// SyntheticLocations indicates an expected call of SyntheticLocations.
func (mr *MockInstanaAPIMockRecorder) SyntheticLocations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyntheticLocations", reflect.TypeOf((*MockInstanaAPI)(nil).SyntheticLocations))
}

// SyntheticTests mocks base method.
func (m *MockInstanaAPI) SyntheticTests() rest.RestResource[*api.SyntheticTest] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyntheticTests")
	ret0, _ := ret[0].(rest.RestResource[*api.SyntheticTest])
	return ret0
}

// SyntheticTests indicates an expected call of SyntheticTests.
func (mr *MockInstanaAPIMockRecorder) SyntheticTests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyntheticTests", reflect.TypeOf((*MockInstanaAPI)(nil).SyntheticTests))
}

// Teams mocks base method.
func (m *MockInstanaAPI) Teams() rest.RestResource[*api.Team] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Teams")
	ret0, _ := ret[0].(rest.RestResource[*api.Team])
	return ret0
}

// Teams indicates an expected call of Teams.
func (mr *MockInstanaAPIMockRecorder) Teams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Teams", reflect.TypeOf((*MockInstanaAPI)(nil).Teams))
}

// Users mocks base method.
func (m *MockInstanaAPI) Users() rest.ReadOnlyRestResource[*api.User] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(rest.ReadOnlyRestResource[*api.User])
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockInstanaAPIMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockInstanaAPI)(nil).Users))
}

// WebsiteAlertConfigs mocks base method.
func (m *MockInstanaAPI) WebsiteAlertConfigs() rest.RestResource[*api.WebsiteAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebsiteAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.WebsiteAlertConfig])
	return ret0
}

// WebsiteAlertConfigs indicates an expected call of WebsiteAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) WebsiteAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebsiteAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).WebsiteAlertConfigs))
}

// WebsiteMonitoringConfigs mocks base method.
func (m *MockInstanaAPI) WebsiteMonitoringConfigs() rest.RestResource[*api.WebsiteMonitoringConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebsiteMonitoringConfigs")
	ret0, _ := ret[0].(rest.RestResource[*api.WebsiteMonitoringConfig])
	return ret0
}

// WebsiteMonitoringConfigs indicates an expected call of WebsiteMonitoringConfigs.
func (mr *MockInstanaAPIMockRecorder) WebsiteMonitoringConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebsiteMonitoringConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).WebsiteMonitoringConfigs))
}
