// Code generated by MockGen. DO NOT EDIT.
// Source: shared/rest/resource.go
//
// Generated by this command:
//
//	mockgen -source=shared/rest/resource.go -destination=mocks/rest-client_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	rest "github.com/instana/instana-go-client/shared/rest"
	gomock "go.uber.org/mock/gomock"
)

// MockInstanaDataObject is a mock of InstanaDataObject interface.
type MockInstanaDataObject struct {
	ctrl     *gomock.Controller
	recorder *MockInstanaDataObjectMockRecorder
	isgomock struct{}
}

// MockInstanaDataObjectMockRecorder is the mock recorder for MockInstanaDataObject.
type MockInstanaDataObjectMockRecorder struct {
	mock *MockInstanaDataObject
}

// NewMockInstanaDataObject creates a new mock instance.
func NewMockInstanaDataObject(ctrl *gomock.Controller) *MockInstanaDataObject {
	mock := &MockInstanaDataObject{ctrl: ctrl}
	mock.recorder = &MockInstanaDataObjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanaDataObject) EXPECT() *MockInstanaDataObjectMockRecorder {
	return m.recorder
}

// GetIDForResourcePath mocks base method.
func (m *MockInstanaDataObject) GetIDForResourcePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDForResourcePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIDForResourcePath indicates an expected call of GetIDForResourcePath.
func (mr *MockInstanaDataObjectMockRecorder) GetIDForResourcePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDForResourcePath", reflect.TypeOf((*MockInstanaDataObject)(nil).GetIDForResourcePath))
}

// MockRestResource is a mock of RestResource interface.
type MockRestResource[T rest.InstanaDataObject] struct {
	ctrl     *gomock.Controller
	recorder *MockRestResourceMockRecorder[T]
	isgomock struct{}
}

// MockRestResourceMockRecorder is the mock recorder for MockRestResource.
type MockRestResourceMockRecorder[T rest.InstanaDataObject] struct {
	mock *MockRestResource[T]
}

// NewMockRestResource creates a new mock instance.
func NewMockRestResource[T rest.InstanaDataObject](ctrl *gomock.Controller) *MockRestResource[T] {
	mock := &MockRestResource[T]{ctrl: ctrl}
	mock.recorder = &MockRestResourceMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestResource[T]) EXPECT() *MockRestResourceMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m *MockRestResource[T]) Create(data T) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRestResourceMockRecorder[T]) Create(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRestResource[T])(nil).Create), data)
}

// Delete mocks base method.
func (m *MockRestResource[T]) Delete(data T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRestResourceMockRecorder[T]) Delete(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRestResource[T])(nil).Delete), data)
}

// DeleteByID mocks base method.
func (m *MockRestResource[T]) DeleteByID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRestResourceMockRecorder[T]) DeleteByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRestResource[T])(nil).DeleteByID), id)
}

// GetAll mocks base method.
func (m *MockRestResource[T]) GetAll() (*[]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRestResourceMockRecorder[T]) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRestResource[T])(nil).GetAll))
}

// GetOne mocks base method.
func (m *MockRestResource[T]) GetOne(id string) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", id)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockRestResourceMockRecorder[T]) GetOne(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockRestResource[T])(nil).GetOne), id)
}

// Update mocks base method.
func (m *MockRestResource[T]) Update(data T) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", data)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRestResourceMockRecorder[T]) Update(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRestResource[T])(nil).Update), data)
}

// MockReadOnlyRestResource is a mock of ReadOnlyRestResource interface.
type MockReadOnlyRestResource[T rest.InstanaDataObject] struct {
	ctrl     *gomock.Controller
	recorder *MockReadOnlyRestResourceMockRecorder[T]
	isgomock struct{}
}

// MockReadOnlyRestResourceMockRecorder is the mock recorder for MockReadOnlyRestResource.
type MockReadOnlyRestResourceMockRecorder[T rest.InstanaDataObject] struct {
	mock *MockReadOnlyRestResource[T]
}

// NewMockReadOnlyRestResource creates a new mock instance.
func NewMockReadOnlyRestResource[T rest.InstanaDataObject](ctrl *gomock.Controller) *MockReadOnlyRestResource[T] {
	mock := &MockReadOnlyRestResource[T]{ctrl: ctrl}
	mock.recorder = &MockReadOnlyRestResourceMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadOnlyRestResource[T]) EXPECT() *MockReadOnlyRestResourceMockRecorder[T] {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockReadOnlyRestResource[T]) GetAll() (*[]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockReadOnlyRestResourceMockRecorder[T]) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockReadOnlyRestResource[T])(nil).GetAll))
}

// GetByQuery mocks base method.
func (m *MockReadOnlyRestResource[T]) GetByQuery(queryParams map[string]string) (*[]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByQuery", queryParams)
	ret0, _ := ret[0].(*[]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByQuery indicates an expected call of GetByQuery.
func (mr *MockReadOnlyRestResourceMockRecorder[T]) GetByQuery(queryParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByQuery", reflect.TypeOf((*MockReadOnlyRestResource[T])(nil).GetByQuery), queryParams)
}

// GetOne mocks base method.
func (m *MockReadOnlyRestResource[T]) GetOne(id string) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", id)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockReadOnlyRestResourceMockRecorder[T]) GetOne(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockReadOnlyRestResource[T])(nil).GetOne), id)
}

// MockJSONUnmarshaller is a mock of JSONUnmarshaller interface.
type MockJSONUnmarshaller[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockJSONUnmarshallerMockRecorder[T]
	isgomock struct{}
}

// MockJSONUnmarshallerMockRecorder is the mock recorder for MockJSONUnmarshaller.
type MockJSONUnmarshallerMockRecorder[T any] struct {
	mock *MockJSONUnmarshaller[T]
}

// NewMockJSONUnmarshaller creates a new mock instance.
func NewMockJSONUnmarshaller[T any](ctrl *gomock.Controller) *MockJSONUnmarshaller[T] {
	mock := &MockJSONUnmarshaller[T]{ctrl: ctrl}
	mock.recorder = &MockJSONUnmarshallerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJSONUnmarshaller[T]) EXPECT() *MockJSONUnmarshallerMockRecorder[T] {
	return m.recorder
}

// Unmarshal mocks base method.
func (m *MockJSONUnmarshaller[T]) Unmarshal(data []byte) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", data)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockJSONUnmarshallerMockRecorder[T]) Unmarshal(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockJSONUnmarshaller[T])(nil).Unmarshal), data)
}

// UnmarshalArray mocks base method.
func (m *MockJSONUnmarshaller[T]) UnmarshalArray(data []byte) (*[]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalArray", data)
	ret0, _ := ret[0].(*[]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalArray indicates an expected call of UnmarshalArray.
func (mr *MockJSONUnmarshallerMockRecorder[T]) UnmarshalArray(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalArray", reflect.TypeOf((*MockJSONUnmarshaller[T])(nil).UnmarshalArray), data)
}

// MockRestClient is a mock of RestClient interface.
type MockRestClient struct {
	ctrl     *gomock.Controller
	recorder *MockRestClientMockRecorder
	isgomock struct{}
}

// MockRestClientMockRecorder is the mock recorder for MockRestClient.
type MockRestClientMockRecorder struct {
	mock *MockRestClient
}

// NewMockRestClient creates a new mock instance.
func NewMockRestClient(ctrl *gomock.Controller) *MockRestClient {
	mock := &MockRestClient{ctrl: ctrl}
	mock.recorder = &MockRestClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestClient) EXPECT() *MockRestClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRestClient) Delete(resourceID, resourceBasePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", resourceID, resourceBasePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRestClientMockRecorder) Delete(resourceID, resourceBasePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRestClient)(nil).Delete), resourceID, resourceBasePath)
}

// Get mocks base method.
func (m *MockRestClient) Get(resourcePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", resourcePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRestClientMockRecorder) Get(resourcePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRestClient)(nil).Get), resourcePath)
}

// GetByQuery mocks base method.
func (m *MockRestClient) GetByQuery(resourcePath string, queryParams map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByQuery", resourcePath, queryParams)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByQuery indicates an expected call of GetByQuery.
func (mr *MockRestClientMockRecorder) GetByQuery(resourcePath, queryParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByQuery", reflect.TypeOf((*MockRestClient)(nil).GetByQuery), resourcePath, queryParams)
}

// GetOne mocks base method.
func (m *MockRestClient) GetOne(id, resourcePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", id, resourcePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockRestClientMockRecorder) GetOne(id, resourcePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockRestClient)(nil).GetOne), id, resourcePath)
}

// Post mocks base method.
func (m *MockRestClient) Post(data rest.InstanaDataObject, resourcePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", data, resourcePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockRestClientMockRecorder) Post(data, resourcePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockRestClient)(nil).Post), data, resourcePath)
}

// PostByQuery mocks base method.
func (m *MockRestClient) PostByQuery(resourcePath string, queryParams map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostByQuery", resourcePath, queryParams)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostByQuery indicates an expected call of PostByQuery.
func (mr *MockRestClientMockRecorder) PostByQuery(resourcePath, queryParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostByQuery", reflect.TypeOf((*MockRestClient)(nil).PostByQuery), resourcePath, queryParams)
}

// PostWithID mocks base method.
func (m *MockRestClient) PostWithID(data rest.InstanaDataObject, resourcePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostWithID", data, resourcePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostWithID indicates an expected call of PostWithID.
func (mr *MockRestClientMockRecorder) PostWithID(data, resourcePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostWithID", reflect.TypeOf((*MockRestClient)(nil).PostWithID), data, resourcePath)
}

// Put mocks base method.
func (m *MockRestClient) Put(data rest.InstanaDataObject, resourcePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", data, resourcePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockRestClientMockRecorder) Put(data, resourcePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRestClient)(nil).Put), data, resourcePath)
}

// PutByQuery mocks base method.
func (m *MockRestClient) PutByQuery(resourcePath, is string, queryParams map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutByQuery", resourcePath, is, queryParams)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutByQuery indicates an expected call of PutByQuery.
func (mr *MockRestClientMockRecorder) PutByQuery(resourcePath, is, queryParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutByQuery", reflect.TypeOf((*MockRestClient)(nil).PutByQuery), resourcePath, is, queryParams)
}
